# Environment for Alice TRF analysis
# usage: $ conda env create --file=environment.yml
name: neuroTools
channels:
- conda-forge
dependencies:
- python
- eelbrain
- pip
- ipython
- jupyter
- jupyterlab
- qtconsole
- jupytext
- ipywidgets
- seaborn
- pyfftw
- pillow
- pyglet
- pysurfer
- librosa
- google-cloud-texttospeech
- pydub
- cython
- sympy
- matplotlib-inline
- mne-kit-gui
- pip:
  - https://github.com/christianbrodbeck/TRF-Tools/archive/main.zip
  - https://github.com/christianbrodbeck/gammatone/archive/fmax.zip
  - mat73
  - pyparallel
  - rtmixer
  - git+https://github.com/labsn/expyfun
  - praat-parselmouth
  - wave
  - git+https://github.com/lerud/cochlea
  - simpleaudio
  - black